[package]
name = "quick_node"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
url = "2.5.4"
ethers = "2.0.14"
tokio = { version = "1", features = ["full"] }
chrono = "0.4.40"
iso8601 = "0.6.2"
lazy_static = "1.5.0"
